---
- name: Main Play
  hosts: localhost
  connection: local
  ignore_errors: True
  roles:
  - { role: elkstatus, tags: ['common'] }
  - { role: checkupgrade,  check_status: 'true' }
#  - { role: checkupgrade,  list_containers : 'true' }

  