# - name: Update the docker-ce to latest
#   apt:
#     name: docker-ce
#     state: latest
#     update_cache: yes
#    become: yes
#    register: out
#    failed_when: out.changed == false
- name: Latest Version of Docker Engine Status
  debug:
    msg: "{{ out_latest_installed_version.stdout | default('1') }}"
- name: Docker Version After Upgarde
  set_fact:
    afterupgrade: "{{ out_latest_installed_version.stdout | default('1') }}"