- name: Installing Latest Version of DE
  shell: sudo apt-get install docker-ce
  become: yes
  register: out_latest_installed_version
- name: Latest Version of Docker Engine Status
  debug:
    msg: "{{ out_latest_installed_version.stdout }}"