- name: "Enable shard allocation for the cluster"
  uri:
    url: http://localhost:{{ es_http_port }}/_cluster/settings
    method: PUT
    body: "{{ es_enable_allocation }}"
    body_format: json
    return_content: yes
    headers:
      Content-Type: "application/json"
  register: enable_shard
  until: enable_shard.content.find('true') != -1
  retries: 10
  delay: 15


  