---
# tasks file for elkstatus
# - name: Check Health After Cluster disbled Allocation
  # include_tasks: ../handlers/main.yml

  
- name: Enable Allocation
  include_tasks: enable_disableall.yaml
  when: enable_allocation == 'true'
  
- name: Handler Call
  command : /bin/true
  notify: Check Cluster Health

- name: Disable Aloocation
  include_tasks: disableallocation.yaml
  when: disable_allocation == 'true'

- name: Handler Call
  command : /bin/true
  notify: Check Cluster Health
